version: '3.6'

services:
  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile-production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/frontend