version: '3.6'

services:
  db:
    image: postgres:11.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /app/myevents/manage.py runserver_plus --cert-file /tmp/cert 0.0.0.0:8000
    container_name: myevents
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: